// Generated by scripts/generate-blog-index.ts. Do not edit by hand.
import type { BlogPost } from "@/content/blog/types";

export const blogPosts: BlogPost[] = [
  {
    "slug": "agentic-research-workbench",
    "title": "Agentic Research Workbench",
    "summary": "A modular workspace for reading papers, extracting structure, generating figures, and turning scattered research artifacts into reusable knowledge.",
    "date": "2026-06-20",
    "readingTime": "1 min read",
    "sourceType": "mdx",
    "href": "/blog/agentic-research-workbench/",
    "image": "/assets/visuals/profile-field.png",
    "category": "Research systems",
    "language": "en",
    "source": {
      "status": "original"
    },
    "tags": [
      "research systems",
      "agents"
    ],
    "featured": true
  },
  {
    "slug": "alphafold3-illustrated-cn",
    "title": "图解 AlphaFold",
    "summary": "一篇 AlphaFold3 架构的中文可视化导览，梳理输入准备、表征学习、结构预测与置信度评估等模块。",
    "date": "2026-06-20",
    "readingTime": "78 min read",
    "sourceType": "html",
    "href": "/blog/alphafold3-illustrated-cn/",
    "image": "/assets/visuals/notes-field.png",
    "category": "Technical explainers",
    "language": "zh",
    "source": {
      "status": "translation",
      "label": "转载 / 翻译",
      "originalTitle": "The Illustrated AlphaFold",
      "originalUrl": "https://elanapearl.github.io/blog/2024/the-illustrated-alphafold/"
    },
    "tags": [
      "AlphaFold3",
      "illustrated note"
    ],
    "featured": true
  },
  {
    "slug": "flow-matching-diffusion-models-cn",
    "title": "流匹配与扩散模型导论",
    "summary": "MIT 6.S184 课程讲义的中文翻译与双语对照版本，系统介绍 flow matching、扩散模型、score matching、guidance、latent diffusion 和离散扩散语言模型。",
    "date": "2026-06-21",
    "readingTime": "84 pages",
    "sourceType": "mdx",
    "href": "/blog/flow-matching-diffusion-models-cn/",
    "image": "/assets/visuals/notes-field.png",
    "category": "Technical explainers",
    "language": "bilingual",
    "source": {
      "status": "translation",
      "label": "转载 / 翻译",
      "originalTitle": "An Introduction to Flow Matching and Diffusion Models",
      "originalUrl": "https://diffusion.csail.mit.edu/"
    },
    "tags": [
      "diffusion models",
      "flow matching",
      "illustrated note"
    ]
  },
  {
    "slug": "publication-profile-design",
    "title": "A publication-first personal profile",
    "summary": "Design notes on turning a personal site into a compact research index with separate spaces for papers, notes, projects, and profile context.",
    "date": "2026-06-18",
    "readingTime": "1 min read",
    "sourceType": "mdx",
    "href": "/blog/publication-profile-design/",
    "image": "/assets/visuals/notes-field.png",
    "category": "Site notes",
    "language": "en",
    "source": {
      "status": "original"
    },
    "tags": [
      "site design",
      "content system"
    ]
  }
];
