// Generated by scripts/generate-blog-index.ts. Do not edit by hand.
import type { BlogPost } from "@/content/blog/types";

export const blogPosts: BlogPost[] = [
  {
    "slug": "alphafold3-illustrated-cn",
    "title": "图解 AlphaFold",
    "summary": "一篇 AlphaFold3 架构的中文可视化导览，梳理输入准备、表征学习、结构预测与置信度评估等模块。",
    "date": "2026-06-20",
    "readingTime": "78 min read",
    "sourceType": "html",
    "href": "/blog/alphafold3-illustrated-cn/",
    "image": "/assets/visuals/profile-field.png",
    "category": "Technical explainers",
    "language": "zh",
    "source": {
      "status": "translation",
      "label": "转载 / 翻译",
      "originalTitle": "The Illustrated AlphaFold",
      "originalUrl": "https://elanapearl.github.io/blog/2024/the-illustrated-alphafold/"
    },
    "tags": [
      "AlphaFold3"
    ],
    "featured": true
  },
  {
    "slug": "flow-matching-diffusion-models-cn",
    "title": "流匹配与扩散模型导论",
    "summary": "MIT 6.S184 课程讲义的中文翻译与双语对照版本，系统介绍 flow matching、扩散模型、score matching、guidance、latent diffusion 和离散扩散语言模型。",
    "date": "2026-06-21",
    "readingTime": "84 pages",
    "sourceType": "mdx",
    "href": "/blog/flow-matching-diffusion-models-cn/",
    "image": "/assets/visuals/profile-field.png",
    "category": "Technical explainers",
    "language": "bilingual",
    "source": {
      "status": "translation",
      "label": "转载 / 翻译",
      "originalTitle": "An Introduction to Flow Matching and Diffusion Models",
      "originalUrl": "https://diffusion.csail.mit.edu/"
    },
    "tags": [
      "diffusion models",
      "flow matching"
    ]
  },
  {
    "slug": "vla-wam-world-models-cn",
    "title": "VLA、世界模型与 WAM：机器人模型到底在学什么",
    "summary": "从学习目标区分 VLA、世界模型与 WAM：VLA 直接生成动作，世界模型预测动作后果，WAM 将动作和未来状态联合建模。",
    "date": "2026-06-23",
    "readingTime": "12 min read",
    "sourceType": "mdx",
    "href": "/blog/vla-wam-world-models-cn/",
    "image": "/assets/blog/vla-wam-world-models-cn/wam-concept.jpg",
    "category": "Technical explainers",
    "language": "zh",
    "source": {
      "status": "original",
      "note": "综合 arXiv、PMLR、OpenReview、NVIDIA Research 等公开论文与项目资料写成。"
    },
    "tags": [
      "world models",
      "physical AI",
      "reinforcement learning"
    ]
  },
  {
    "slug": "what-are-world-models-cn",
    "title": "什么是世界模型",
    "summary": "从 Ha 与 Schmidhuber 的 V-M-C 架构，到 Genie、V-JEPA、PAN 和 NVIDIA 的物理 AI 视角，梳理世界模型的定义、公式、路线和边界。",
    "date": "2026-06-21",
    "readingTime": "7 min read",
    "sourceType": "mdx",
    "href": "/blog/what-are-world-models-cn/",
    "image": "/assets/blog/world-models-cn/three-paradigms.jpg",
    "category": "Technical explainers",
    "language": "zh",
    "source": {
      "status": "original",
      "note": "综合本地课件、Edmund Goodman 讲义和 NVIDIA Glossary 写成。"
    },
    "tags": [
      "world models",
      "physical AI",
      "reinforcement learning"
    ]
  }
];
