// Generated by scripts/generate-blog-index.ts. Do not edit by hand.
import type { ComponentType } from "react";
import AgenticResearchWorkbench from "@/content/blog/posts/agentic-research-workbench/index.mdx";
import PublicationProfileDesign from "@/content/blog/posts/publication-profile-design/index.mdx";

export const blogPostContent: Record<string, ComponentType> = {
  "agentic-research-workbench": AgenticResearchWorkbench,
  "publication-profile-design": PublicationProfileDesign
};
