// Generated by scripts/generate-blog-index.ts. Do not edit by hand.
import type { ComponentType } from "react";
import FlowMatchingDiffusionModelsCn from "@/content/blog/posts/flow-matching-diffusion-models-cn/index.mdx";
import VlaWamWorldModelsCn from "@/content/blog/posts/vla-wam-world-models-cn/index.mdx";
import WhatAreWorldModelsCn from "@/content/blog/posts/what-are-world-models-cn/index.mdx";
import WorldModelsGuideActionCn from "@/content/blog/posts/world-models-guide-action-cn/index.mdx";

export const blogPostContent: Record<string, ComponentType> = {
  "flow-matching-diffusion-models-cn": FlowMatchingDiffusionModelsCn,
  "vla-wam-world-models-cn": VlaWamWorldModelsCn,
  "what-are-world-models-cn": WhatAreWorldModelsCn,
  "world-models-guide-action-cn": WorldModelsGuideActionCn
};
