// Generated by scripts/generate-blog-index.ts. Do not edit by hand.
import type { ComponentType } from "react";
import AdaworldLatentActions from "@/content/blog/posts/adaworld-latent-actions/index.mdx";
import FlowMatchingDiffusionModelsCn from "@/content/blog/posts/flow-matching-diffusion-models-cn/index.mdx";
import WhatAreWorldModelsCn from "@/content/blog/posts/what-are-world-models-cn/index.mdx";

export const blogPostContent: Record<string, ComponentType> = {
  "adaworld-latent-actions": AdaworldLatentActions,
  "flow-matching-diffusion-models-cn": FlowMatchingDiffusionModelsCn,
  "what-are-world-models-cn": WhatAreWorldModelsCn
};
