import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import type { BlogPost, BlogPostMeta } from "../content/blog/types";

const repoRoot = fileURLToPath(new URL("..", import.meta.url));
const postsRoot = path.join(repoRoot, "content/blog/posts");
const generatedRoot = path.join(repoRoot, ".generated");
const postsOutput = path.join(generatedRoot, "blog-posts.ts");
const contentOutput = path.join(generatedRoot, "blog-post-content.ts");

function pascalCase(value: string) {
  return value
    .split(/[^a-zA-Z0-9]/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function estimateReadingTime(source: string) {
  const text = source
    .replace(/```[\s\S]*?```/g, " ")
    .replace(/<[^>]*>/g, " ")
    .replace(/[^\p{L}\p{N}\s]/gu, " ");
  const cjk = text.match(/[\u3400-\u9fff]/g)?.length ?? 0;
  const words = text.replace(/[\u3400-\u9fff]/g, " ").match(/[A-Za-z0-9]+/g)?.length ?? 0;
  const minutes = Math.max(1, Math.ceil(words / 220 + cjk / 500));

  return `${minutes} min read`;
}

async function exists(filePath: string) {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function loadMeta(slug: string) {
  const metaPath = path.join(postsRoot, slug, "meta.ts");
  const moduleUrl = `${pathToFileURL(metaPath).href}?t=${Date.now()}`;
  const imported = (await import(moduleUrl)) as { default?: BlogPostMeta };

  if (!imported.default) {
    throw new Error(`Missing default export in ${path.relative(repoRoot, metaPath)}`);
  }

  return imported.default;
}

async function normalizePost(slug: string): Promise<BlogPost> {
  const postDir = path.join(postsRoot, slug);
  const meta = await loadMeta(slug);
  const href =
    meta.href ?? (meta.sourceType === "external" ? undefined : `/blog/${slug}/`);

  if (!href) {
    throw new Error(`${slug}: external posts must provide href`);
  }

  let readingTime = meta.readingTime;
  const mdxPath = path.join(postDir, "index.mdx");

  if (!readingTime && meta.sourceType === "mdx" && (await exists(mdxPath))) {
    readingTime = estimateReadingTime(await fs.readFile(mdxPath, "utf8"));
  }

  return {
    slug,
    title: meta.title,
    summary: meta.summary,
    date: meta.date,
    readingTime: readingTime ?? "External",
    sourceType: meta.sourceType,
    href,
    ...(meta.image ? { image: meta.image } : {}),
    ...(meta.badge ? { badge: meta.badge } : {}),
    ...(meta.category ? { category: meta.category } : {}),
    ...(meta.language ? { language: meta.language } : {}),
    ...(meta.source ? { source: meta.source } : {}),
    ...(meta.tags?.length ? { tags: meta.tags } : {}),
    ...(meta.featured ? { featured: true } : {}),
    ...(meta.listed === false ? { listed: false } : {}),
    ...(meta.updated ? { updated: meta.updated } : {})
  };
}

async function main() {
  const entries = await fs.readdir(postsRoot, { withFileTypes: true });
  const slugs = entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
  const posts = await Promise.all(slugs.map((slug) => normalizePost(slug)));
  const mdxPosts = posts.filter((post) => post.sourceType === "mdx");
  const contentImports = mdxPosts
    .map((post) => {
      const component = pascalCase(post.slug);
      return `import ${component} from "@/content/blog/posts/${post.slug}/index.mdx";`;
    })
    .join("\n");
  const contentEntries = mdxPosts
    .map((post) => `  "${post.slug}": ${pascalCase(post.slug)}`)
    .join(",\n");

  await fs.mkdir(generatedRoot, { recursive: true });
  await fs.writeFile(
    postsOutput,
    `// Generated by scripts/generate-blog-index.ts. Do not edit by hand.\nimport type { BlogPost } from "@/content/blog/types";\n\nexport const blogPosts: BlogPost[] = ${JSON.stringify(posts, null, 2)};\n`,
    "utf8"
  );
  await fs.writeFile(
    contentOutput,
    `// Generated by scripts/generate-blog-index.ts. Do not edit by hand.\nimport type { ComponentType } from "react";\n${contentImports}\n\nexport const blogPostContent: Record<string, ComponentType> = {\n${contentEntries}\n};\n`,
    "utf8"
  );

  console.log(`Generated ${posts.length} blog posts.`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
