import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { BilingualArticleContent } from "../components/bilingual-article-content";
import { lectureNotesSegments } from "../content/blog/posts/flow-matching-diffusion-models-cn/segments";

const repoRoot = fileURLToPath(new URL("..", import.meta.url));
const outputPath = path.join(
  repoRoot,
  "public/blog/flow-matching-diffusion-models-cn/segments.json"
);
const generatedModulePath = path.join(repoRoot, ".generated/bilingual-articles.ts");

async function main() {
  const initialHtml = renderToStaticMarkup(
    createElement(BilingualArticleContent, {
      mode: "zh",
      segments: lectureNotesSegments
    })
  );

  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, JSON.stringify(lectureNotesSegments), "utf8");
  await fs.mkdir(path.dirname(generatedModulePath), { recursive: true });
  await fs.writeFile(
    generatedModulePath,
    `// Generated by scripts/generate-bilingual-assets.ts. Do not edit by hand.\nexport const flowMatchingZhHtml = ${JSON.stringify(initialHtml)};\n`,
    "utf8"
  );

  console.log(
    `Generated ${path.relative(repoRoot, outputPath)} and ${path.relative(
      repoRoot,
      generatedModulePath
    )}.`
  );
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
